/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    faqs: Faq;
    media: Media;
    leads: Lead;
    'feedback-requests': FeedbackRequest;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'feedback-requests': FeedbackRequestsSelect<false> | FeedbackRequestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Part of the web address. Filled in automatically from the title.
   */
  slug?: string | null;
  layout?:
    | (
        | HeroBlock
        | StatementBlock
        | ClientLogosBlock
        | ProofStatsBlock
        | SelectedWorkBlock
        | WhyZeetechBlock
        | ClientStoriesBlock
        | HowWeDeliverBlock
        | HowWeBuildBlock
        | DeliveryPrinciplesBlock
        | ComparisonBlock
        | ShowreelBlock
        | FaqBlock
        | ProjectInquiryBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  trust?: {
    prefix?: string | null;
    badge?: string | null;
    suffix?: string | null;
    avatars?: (number | Media)[] | null;
  };
  headline: {
    line1: string;
    line2?: string | null;
    /**
     * Start of the last line
     */
    line3?: string | null;
    /**
     * Words on the orange highlight
     */
    highlight?: string | null;
  };
  lede?: string | null;
  primaryCta?: {
    label?: string | null;
    /**
     * e.g. #contact, /work, https://…
     */
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * e.g. #contact, /work, https://…
     */
    href?: string | null;
  };
  /**
   * Project images for the rotating collage (6–12 works best).
   */
  collage?: (number | Media)[] | null;
  showBackdropControls?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * Images, short videos and caption files used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and Google. Leave empty for decoration.
   */
  alt?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock".
 */
export interface StatementBlock {
  line1: string;
  line2?: string | null;
  /**
   * Orange italic words with the hand-drawn underline
   */
  accent?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientLogosBlock".
 */
export interface ClientLogosBlock {
  title: string;
  /**
   * Logos are split into two scrolling rows. Transparent PNG or SVG, about 40px tall.
   */
  logos?:
    | {
        name: string;
        /**
         * Optional link
         */
        url?: string | null;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'clientLogos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProofStatsBlock".
 */
export interface ProofStatsBlock {
  /**
   * The featured quote (photo, name, role and quote come from the testimonial).
   */
  testimonial?: (number | null) | Testimonial;
  rating?: {
    value?: number | null;
    icon?: (number | null) | Media;
  };
  awards?:
    | {
        label: string;
        image?: (number | null) | Media;
        round?: boolean | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: number;
        /**
         * +, %, …
         */
        suffix?: string | null;
        label: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'proofStats';
}
/**
 * Client feedback — written or video. Feedback sent in through a feedback link arrives here as a draft; review it and press Publish to show it on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  _order?: string | null;
  name: string;
  company?: string | null;
  /**
   * e.g. VP of Engineering
   */
  role?: string | null;
  /**
   * Portrait used on the slide.
   */
  photo?: (number | null) | Media;
  quote: string;
  type?: ('text' | 'video') | null;
  video?: {
    source?: ('none' | 'upload' | 'youtube' | 'vimeo' | 'bunny' | 'url') | null;
    /**
     * Keep uploads short (under ~50 MB). Host longer videos on Bunny Stream or YouTube.
     */
    file?: (number | null) | Media;
    /**
     * Paste the share link (YouTube / Vimeo) or the embed URL from Bunny Stream.
     */
    url?: string | null;
    /**
     * Still image shown before the video plays.
     */
    poster?: (number | null) | Media;
    /**
     * Optional WebVTT (.vtt) subtitles for uploaded videos.
     */
    captions?: (number | null) | Media;
    /**
     * What is said in the video. Helps accessibility and SEO.
     */
    transcript?: string | null;
  };
  /**
   * Where the review was originally left. Shown as a small badge.
   */
  source?: {
    platform?: ('upwork' | 'fiverr' | 'clutch' | 'google' | 'linkedin' | 'direct') | null;
    rating?: number | null;
    reviewUrl?: string | null;
    /**
     * Platform logo chip shown after the quote.
     */
    logo?: (number | null) | Media;
    /**
     * Optional award / crest shown next to the name.
     */
    badge?: (number | null) | Media;
  };
  /**
   * Highlight in the top proof section.
   */
  featured?: boolean | null;
  origin?: ('admin' | 'client') | null;
  consent?: boolean | null;
  feedbackRequest?: (number | null) | FeedbackRequest;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Create a request, then copy the private link (or tick “Email the link”) and send it to your client.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-requests".
 */
export interface FeedbackRequest {
  id: number;
  clientName: string;
  company?: string | null;
  clientEmail?: string | null;
  /**
   * Shown to the client on the form, e.g. “FleetPulse dispatch platform”.
   */
  project?: string | null;
  /**
   * Copy this link and send it to the client.
   */
  shareLink?: string | null;
  /**
   * Needs SMTP to be set up on the server.
   */
  emailClient?: boolean | null;
  status?: ('open' | 'submitted' | 'closed') | null;
  /**
   * The link stops working after this date.
   */
  expiresAt?: string | null;
  invitedAt?: string | null;
  /**
   * Created when the client submits.
   */
  testimonial?: (number | null) | Testimonial;
  token?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SelectedWorkBlock".
 */
export interface SelectedWorkBlock {
  eyebrow?: string | null;
  /**
   * Grey line under the eyebrow
   */
  note?: string | null;
  title: string;
  accent?: string | null;
  button?: {
    label?: string | null;
    /**
     * e.g. #contact, /work, https://…
     */
    href?: string | null;
  };
  /**
   * Choose and order the cards. Leave empty to show the latest five.
   */
  caseStudies?: (number | CaseStudy)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'selectedWork';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Part of the web address. Filled in automatically from the title.
   */
  slug?: string | null;
  /**
   * e.g. Project 01
   */
  projectLabel?: string | null;
  /**
   * e.g. FleetPulse Global
   */
  client?: string | null;
  /**
   * Card colour (hex), e.g. #ff8648
   */
  color?: string | null;
  summary?: string | null;
  scope?: string | null;
  duration?: string | null;
  cover: number | Media;
  person?: {
    name?: string | null;
    role?: string | null;
    avatar?: (number | null) | Media;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?: (number | Media)[] | null;
  testimonial?: (number | null) | Testimonial;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyZeetechBlock".
 */
export interface WhyZeetechBlock {
  heading: {
    /**
     * Small label above the title
     */
    eyebrow?: string | null;
    /**
     * Main part of the title
     */
    title: string;
    /**
     * Orange italic part that follows the title
     */
    accent?: string | null;
    accentOnNewLine?: boolean | null;
    subtitle?: string | null;
  };
  /**
   * Until a video is added, an animated wave plays in the frame.
   */
  reel?: {
    source?: ('none' | 'upload' | 'youtube' | 'vimeo' | 'bunny' | 'url') | null;
    /**
     * Keep uploads short (under ~50 MB). Host longer videos on Bunny Stream or YouTube.
     */
    file?: (number | null) | Media;
    /**
     * Paste the share link (YouTube / Vimeo) or the embed URL from Bunny Stream.
     */
    url?: string | null;
    /**
     * Still image shown before the video plays.
     */
    poster?: (number | null) | Media;
    /**
     * Optional WebVTT (.vtt) subtitles for uploaded videos.
     */
    captions?: (number | null) | Media;
    /**
     * What is said in the video. Helps accessibility and SEO.
     */
    transcript?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'whyZeetech';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientStoriesBlock".
 */
export interface ClientStoriesBlock {
  heading: {
    /**
     * Small label above the title
     */
    eyebrow?: string | null;
    /**
     * Main part of the title
     */
    title: string;
    /**
     * Orange italic part that follows the title
     */
    accent?: string | null;
    accentOnNewLine?: boolean | null;
  };
  /**
   * Short line next to the arrows
   */
  note?: string | null;
  /**
   * Choose and order the slides. Leave empty to show all published testimonials.
   */
  testimonials?: (number | Testimonial)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'clientStories';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowWeDeliverBlock".
 */
export interface HowWeDeliverBlock {
  heading: {
    /**
     * Small label above the title
     */
    eyebrow?: string | null;
    /**
     * Main part of the title
     */
    title: string;
    /**
     * Orange italic part that follows the title
     */
    accent?: string | null;
    /**
     * Orange (not italic) words placed just before the accent
     */
    highlight?: string | null;
    accentOnNewLine?: boolean | null;
    subtitle?: string | null;
  };
  /**
   * Default preview image on the right.
   */
  preview?: (number | null) | Media;
  services?:
    | {
        title: string;
        description?: string | null;
        /**
         * e.g. 01 / ARCHITECTURE
         */
        tag?: string | null;
        /**
         * Optional preview for this service
         */
        image?: (number | null) | Media;
        link?: {
          label?: string | null;
          /**
           * e.g. #contact, /work, https://…
           */
          href?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'howWeDeliver';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowWeBuildBlock".
 */
export interface HowWeBuildBlock {
  heading: {
    /**
     * Small label above the title
     */
    eyebrow?: string | null;
    /**
     * Main part of the title
     */
    title: string;
    /**
     * Orange italic part that follows the title
     */
    accent?: string | null;
    accentOnNewLine?: boolean | null;
    subtitle?: string | null;
  };
  /**
   * Tool logos drifting behind the map.
   */
  toolIcons?: (number | Media)[] | null;
  /**
   * The connector lines are drawn for six stages.
   */
  stages?:
    | {
        title: string;
        tools?: (number | Media)[] | null;
        /**
         * Press Enter after each item
         */
        delivers?: string[] | null;
        id?: string | null;
      }[]
    | null;
  footerText?: string | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. #contact, /work, https://…
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'howWeBuild';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DeliveryPrinciplesBlock".
 */
export interface DeliveryPrinciplesBlock {
  heading: {
    /**
     * Small label above the title
     */
    eyebrow?: string | null;
    /**
     * Main part of the title
     */
    title: string;
    /**
     * Orange italic part that follows the title
     */
    accent?: string | null;
    accentOnNewLine?: boolean | null;
    subtitle?: string | null;
  };
  cards?:
    | {
        kicker?: string | null;
        title: string;
        accent?: string | null;
        description?: string | null;
        link?: {
          label?: string | null;
          /**
           * e.g. #contact, /work, https://…
           */
          href?: string | null;
        };
        theme?: ('dark' | 'white' | 'yellow' | 'blue' | 'pink' | 'purple') | null;
        visual?: ('image' | 'fill' | 'orbit') | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'deliveryPrinciples';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonBlock".
 */
export interface ComparisonBlock {
  heading: {
    /**
     * Small label above the title
     */
    eyebrow?: string | null;
    /**
     * Main part of the title
     */
    title: string;
    /**
     * Orange italic part that follows the title
     */
    accent?: string | null;
    accentOnNewLine?: boolean | null;
    subtitle?: string | null;
  };
  firstColumnLabel?: string | null;
  /**
   * Column headings, e.g. Strategy, Design, …
   */
  columns?: string[] | null;
  rows?:
    | {
        name: string;
        /**
         * Green highlighted row (ZeeTech)
         */
        highlight?: boolean | null;
        description?: string | null;
        icon?: (number | null) | Media;
        /**
         * Icon ring colour
         */
        ring?: ('orange' | 'green' | 'lime' | 'yellow') | null;
        /**
         * One mark per column, in the same order as the column headings.
         */
        cells?:
          | {
              mark: 'yes' | 'check' | 'dot' | 'no';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparison';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowreelBlock".
 */
export interface ShowreelBlock {
  heading: {
    /**
     * Small label above the title
     */
    eyebrow?: string | null;
    /**
     * Main part of the title
     */
    title: string;
    /**
     * Orange italic part that follows the title
     */
    accent?: string | null;
    accentOnNewLine?: boolean | null;
    subtitle?: string | null;
  };
  /**
   * Words in the top strip
   */
  topTicker?: string[] | null;
  images?: (number | Media)[] | null;
  /**
   * Words in the bottom strip
   */
  bottomTicker?: string[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'showreel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  heading: {
    /**
     * Small label above the title
     */
    eyebrow?: string | null;
    /**
     * Main part of the title
     */
    title: string;
    /**
     * Orange italic part that follows the title
     */
    accent?: string | null;
    accentOnNewLine?: boolean | null;
    subtitle?: string | null;
  };
  helpCard?: {
    background?: (number | null) | Media;
    avatars?: (number | Media)[] | null;
    title?: string | null;
    accent?: string | null;
    text?: string | null;
    cta?: {
      label?: string | null;
      /**
       * e.g. #contact, /work, https://…
       */
      href?: string | null;
    };
  };
  /**
   * Choose and order the questions. Leave empty to show all FAQs.
   */
  faqs?: (number | Faq)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  _order?: string | null;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectInquiryBlock".
 */
export interface ProjectInquiryBlock {
  heading: {
    /**
     * Small label above the title
     */
    eyebrow?: string | null;
    /**
     * Main part of the title
     */
    title: string;
    /**
     * Orange italic part that follows the title
     */
    accent?: string | null;
    accentOnNewLine?: boolean | null;
    subtitle?: string | null;
  };
  prep?: {
    eyebrow?: string | null;
    title?: string | null;
    steps?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    person?: {
      photo?: (number | null) | Media;
      name?: string | null;
      role?: string | null;
    };
  };
  /**
   * Budget choices, e.g. Less than $5k
   */
  budgets?: string[] | null;
  submitLabel?: string | null;
  successMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectInquiry';
}
/**
 * Project inquiries sent through the website form, with where each visitor came from.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  budget?: string | null;
  details: string;
  status?: ('new' | 'contacted' | 'proposal' | 'won' | 'lost') | null;
  notes?: string | null;
  attribution?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
    clickId?: string | null;
    referrer?: string | null;
    landingPage?: string | null;
    formPage?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'feedback-requests';
        value: number | FeedbackRequest;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        clientLogos?: T | ClientLogosBlockSelect<T>;
        proofStats?: T | ProofStatsBlockSelect<T>;
        selectedWork?: T | SelectedWorkBlockSelect<T>;
        whyZeetech?: T | WhyZeetechBlockSelect<T>;
        clientStories?: T | ClientStoriesBlockSelect<T>;
        howWeDeliver?: T | HowWeDeliverBlockSelect<T>;
        howWeBuild?: T | HowWeBuildBlockSelect<T>;
        deliveryPrinciples?: T | DeliveryPrinciplesBlockSelect<T>;
        comparison?: T | ComparisonBlockSelect<T>;
        showreel?: T | ShowreelBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        projectInquiry?: T | ProjectInquiryBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  trust?:
    | T
    | {
        prefix?: T;
        badge?: T;
        suffix?: T;
        avatars?: T;
      };
  headline?:
    | T
    | {
        line1?: T;
        line2?: T;
        line3?: T;
        highlight?: T;
      };
  lede?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  collage?: T;
  showBackdropControls?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock_select".
 */
export interface StatementBlockSelect<T extends boolean = true> {
  line1?: T;
  line2?: T;
  accent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientLogosBlock_select".
 */
export interface ClientLogosBlockSelect<T extends boolean = true> {
  title?: T;
  logos?:
    | T
    | {
        name?: T;
        url?: T;
        logo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProofStatsBlock_select".
 */
export interface ProofStatsBlockSelect<T extends boolean = true> {
  testimonial?: T;
  rating?:
    | T
    | {
        value?: T;
        icon?: T;
      };
  awards?:
    | T
    | {
        label?: T;
        image?: T;
        round?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        note?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SelectedWorkBlock_select".
 */
export interface SelectedWorkBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  note?: T;
  title?: T;
  accent?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  caseStudies?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyZeetechBlock_select".
 */
export interface WhyZeetechBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        accent?: T;
        accentOnNewLine?: T;
        subtitle?: T;
      };
  reel?:
    | T
    | {
        source?: T;
        file?: T;
        url?: T;
        poster?: T;
        captions?: T;
        transcript?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientStoriesBlock_select".
 */
export interface ClientStoriesBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        accent?: T;
        accentOnNewLine?: T;
      };
  note?: T;
  testimonials?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowWeDeliverBlock_select".
 */
export interface HowWeDeliverBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        accent?: T;
        highlight?: T;
        accentOnNewLine?: T;
        subtitle?: T;
      };
  preview?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        tag?: T;
        image?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowWeBuildBlock_select".
 */
export interface HowWeBuildBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        accent?: T;
        accentOnNewLine?: T;
        subtitle?: T;
      };
  toolIcons?: T;
  stages?:
    | T
    | {
        title?: T;
        tools?: T;
        delivers?: T;
        id?: T;
      };
  footerText?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DeliveryPrinciplesBlock_select".
 */
export interface DeliveryPrinciplesBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        accent?: T;
        accentOnNewLine?: T;
        subtitle?: T;
      };
  cards?:
    | T
    | {
        kicker?: T;
        title?: T;
        accent?: T;
        description?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        theme?: T;
        visual?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonBlock_select".
 */
export interface ComparisonBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        accent?: T;
        accentOnNewLine?: T;
        subtitle?: T;
      };
  firstColumnLabel?: T;
  columns?: T;
  rows?:
    | T
    | {
        name?: T;
        highlight?: T;
        description?: T;
        icon?: T;
        ring?: T;
        cells?:
          | T
          | {
              mark?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowreelBlock_select".
 */
export interface ShowreelBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        accent?: T;
        accentOnNewLine?: T;
        subtitle?: T;
      };
  topTicker?: T;
  images?: T;
  bottomTicker?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        accent?: T;
        accentOnNewLine?: T;
        subtitle?: T;
      };
  helpCard?:
    | T
    | {
        background?: T;
        avatars?: T;
        title?: T;
        accent?: T;
        text?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  faqs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectInquiryBlock_select".
 */
export interface ProjectInquiryBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        accent?: T;
        accentOnNewLine?: T;
        subtitle?: T;
      };
  prep?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        person?:
          | T
          | {
              photo?: T;
              name?: T;
              role?: T;
            };
      };
  budgets?: T;
  submitLabel?: T;
  successMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  projectLabel?: T;
  client?: T;
  color?: T;
  summary?: T;
  scope?: T;
  duration?: T;
  cover?: T;
  person?:
    | T
    | {
        name?: T;
        role?: T;
        avatar?: T;
      };
  body?: T;
  gallery?: T;
  testimonial?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  company?: T;
  role?: T;
  photo?: T;
  quote?: T;
  type?: T;
  video?:
    | T
    | {
        source?: T;
        file?: T;
        url?: T;
        poster?: T;
        captions?: T;
        transcript?: T;
      };
  source?:
    | T
    | {
        platform?: T;
        rating?: T;
        reviewUrl?: T;
        logo?: T;
        badge?: T;
      };
  featured?: T;
  origin?: T;
  consent?: T;
  feedbackRequest?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  budget?: T;
  details?: T;
  status?: T;
  notes?: T;
  attribution?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        clickId?: T;
        referrer?: T;
        landingPage?: T;
        formPage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-requests_select".
 */
export interface FeedbackRequestsSelect<T extends boolean = true> {
  clientName?: T;
  company?: T;
  clientEmail?: T;
  project?: T;
  shareLink?: T;
  emailClient?: T;
  status?: T;
  expiresAt?: T;
  invitedAt?: T;
  testimonial?: T;
  token?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  links?:
    | {
        link?: {
          label?: string | null;
          /**
           * e.g. #contact, /work, https://…
           */
          href?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. #contact, /work, https://…
     */
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  pitch?: {
    kicker?: string | null;
    title?: string | null;
    tagline?: string | null;
  };
  emailLabel?: string | null;
  email?: string | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. #contact, /work, https://…
     */
    href?: string | null;
  };
  brand?: {
    text?: string | null;
    location?: string | null;
  };
  columns?:
    | {
        title: string;
        /**
         * Leave the address empty for plain text (e.g. a city name).
         */
        links?:
          | {
              link?: {
                label?: string | null;
                /**
                 * e.g. #contact, /work, https://…
                 */
                href?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  strip?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  bottom?: {
    metaLeft?: string | null;
    metaRight?: string | null;
    copyright?: string | null;
    builtWith?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  /**
   * %s is replaced by the page title.
   */
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  /**
   * Used when a page has no share image of its own (1200 × 630).
   */
  defaultShareImage?: (number | null) | Media;
  legalName?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  socials?:
    | {
        platform?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  gtmId?: string | null;
  /**
   * Only needed if GA4 is not set up inside Tag Manager.
   */
  ga4Id?: string | null;
  metaPixelId?: string | null;
  linkedinPartnerId?: string | null;
  /**
   * Only the content="…" value.
   */
  searchConsoleToken?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  links?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  pitch?:
    | T
    | {
        kicker?: T;
        title?: T;
        tagline?: T;
      };
  emailLabel?: T;
  email?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  brand?:
    | T
    | {
        text?: T;
        location?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  strip?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  bottom?:
    | T
    | {
        metaLeft?: T;
        metaRight?: T;
        copyright?: T;
        builtWith?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultShareImage?: T;
  legalName?: T;
  email?: T;
  phone?: T;
  address?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  gtmId?: T;
  ga4Id?: T;
  metaPixelId?: T;
  linkedinPartnerId?: T;
  searchConsoleToken?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}